export const ROLES = {
  ADMIN: 'Admin',
  HR: 'HR',
  RECRUITER: 'Recruiter',
  MANAGER: 'Manager',
  EMPLOYEE: 'Employee',
  CANDIDATE: 'Candidate',
}

export const hasRole = (userRoles, ...allowedRoles) =>
  allowedRoles.some((r) => userRoles.includes(r))

export const PERMISSIONS = {
  // Users
  MANAGE_USERS: [ROLES.ADMIN],
  VIEW_USERS: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER],

  // Employees
  VIEW_ALL_EMPLOYEES: [ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],
  MANAGE_EMPLOYEES: [ROLES.ADMIN, ROLES.HR],
  VIEW_OWN_PROFILE: [ROLES.EMPLOYEE],

  // Jobs
  VIEW_JOBS: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER, ROLES.MANAGER, ROLES.EMPLOYEE],
  MANAGE_JOBS: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER],
  DELETE_JOB: [ROLES.ADMIN, ROLES.HR],

  // Applications
  VIEW_ALL_APPLICATIONS: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER, ROLES.MANAGER],
  VIEW_OWN_APPLICATIONS: [ROLES.CANDIDATE],
  CREATE_APPLICATION: [ROLES.CANDIDATE],
  UPDATE_APPLICATION_STATUS: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER],

  // Screening
  VIEW_SCREENINGS: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER],
  MANAGE_SCREENINGS: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER],

  // Interviews
  MANAGE_INTERVIEWS: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER],
  VIEW_INTERVIEWS: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER, ROLES.MANAGER],
  UPDATE_INTERVIEW_STATUS: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER, ROLES.MANAGER],

  // Selections
  VIEW_SELECTIONS: [ROLES.ADMIN, ROLES.HR],
  MANAGE_SELECTIONS: [ROLES.ADMIN, ROLES.HR],

  // Performance
  VIEW_ALL_REVIEWS: [ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],
  VIEW_OWN_REVIEWS: [ROLES.EMPLOYEE],
  MANAGE_REVIEWS: [ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],

  // Career Plans
  VIEW_ALL_CAREER_PLANS: [ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],
  VIEW_OWN_CAREER_PLAN: [ROLES.EMPLOYEE],
  MANAGE_CAREER_PLANS: [ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],

  // Training
  VIEW_TRAININGS: [ROLES.ADMIN, ROLES.HR, ROLES.MANAGER, ROLES.EMPLOYEE],
  MANAGE_TRAININGS: [ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],

  // Enrollments
  VIEW_OWN_ENROLLMENTS: [ROLES.EMPLOYEE],
  MANAGE_ENROLLMENTS: [ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],

  // Succession
  MANAGE_SUCCESSION: [ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],

  // Compliance
  MANAGE_COMPLIANCE: [ROLES.ADMIN, ROLES.HR],

  // Audit
  VIEW_AUDITS: [ROLES.ADMIN, ROLES.HR],
  VIEW_AUDIT_LOGS: [ROLES.ADMIN],

  // Reports
  VIEW_REPORTS: [ROLES.ADMIN, ROLES.HR, ROLES.MANAGER],
  MANAGE_REPORTS: [ROLES.ADMIN, ROLES.HR],

  // Resume
  MANAGE_OWN_RESUME: [ROLES.CANDIDATE],
  VIEW_ALL_RESUMES: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER],

  // Notifications
  VIEW_OWN_NOTIFICATIONS: [ROLES.ADMIN, ROLES.HR, ROLES.RECRUITER, ROLES.MANAGER, ROLES.EMPLOYEE, ROLES.CANDIDATE],
}
